version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Munis-DB
      POSTGRES_DB: blogbuddy

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  auth:
    build:
      context: ./
      dockerfile: ./apps/auth/Dockerfile
    env_file:
      - .env
    depends_on:
      - db
      - kafka
    volumes:
      - .:/usr/src/app # any change to base folder should be reflected
      - /usr/src/app/node_modules
    command: npm run start:dev auth

  posts:
    build:
      context: ./
      dockerfile: ./apps/posts/Dockerfile
    env_file:
      - .env
    depends_on:
      - db
      - kafka
    volumes:
      - .:/usr/src/app # any change to base folder should be reflected
      - /usr/src/app/node_modules
    command: npm run start:dev posts

  api:
    build:
      context: ./
      dockerfile: ./apps/api/Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db
      - kafka
      - auth
      - posts
    volumes:
      - .:/usr/src/app # any change to base folder should be reflected
      - /usr/src/app/node_modules
    command: npm run start:dev api

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
